name: plantiq
description: "A new Flutter project."
# Evitar publicación accidental
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  http: ^1.2.2
  provider: ^6.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: true
  image_path: 'assets/icon/app_logo.png'
  adaptive_icon_background: "#1C1F2A"
  adaptive_icon_foreground: "assets/icon/app_logo.png"
