version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: PlantIQ2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ns200622rd*
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:Ns200622rd*@db:5432/PlantIQ2
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app

volumes:
  pgdata:
